apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile
  #labels:
  #  type: local
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /data/dockerfiles