apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/stocks-analyser/stocks-gitops-infra"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pgdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      