apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stocks-data-sync-app
  namespace: argocd
spec:
  source:
    targetRevision: dev
    path: deploy/argocd/environments/development
    