---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: postgres
spec:
  encryptedData:
    password: AgCCQARKYcYfo2St12blQAO99+qdoXblFcxj+gEhwZMonk+k00xq97BgsDhX3IpRUSnXOQktk+DpzqNIo0uMqDcLpheVR7Q60cKHecACyqB+BdphB1WWPu/yRM4PZfT/nOECmVBiJ+JsI8Qam6ejaz9MZVPz1s2uEvb60LjCshsLDMipZjSaGNZjp16pyfCsBAN0JfelEIC8AT2iO33O5rFPlYNKVlqr4oZbIniG4IR2CqoL6ClIX0jt/21TACZY4e220La2IYAof+uxOkFtOyABzBg4Xs+b+gdFQ1JdJSBchygjRIr6TPf6G1lCE7DGe0Xd69asuTcx5T6fR5a0qdTLj5q8M5PFvD+Pz7dSbdSIVPTKx320z6HpIVIjNX5sQTKz2L5P61Ykgt4606U0ftLSdGe1KNoCVeqstsEwy758SnvzoAVCAFoU22+qoiszv6NAD6QPMdZQ6g4L0Qn71Zm1Nj3ThX5zzoMJ4VQu4NbY2nJKKIB/gJzzn49yqYpL4EtAFH4dSJ0m/7G+AviSFWz66Vp9xwcTI9VAow4mOhFDYCjjLFhU7MtYtqoE0JXnSSXiVhrn6WYTy0+YY0VYjOGOqIUiBSfZrkNmH+i6zSOI/Du/UOSlPgr7buK+W7AedNFYkvF2tJmExf1TzrIo0BU5d4OvkxlYp/cqqeyx0a1+QdIwQgCWBn5Scu7rjB/8t3gku0EU
    postgres-password: AgC+sMGwISjZThyvURUBBVHUcP1DkU0US+mOQOkLjXeUr7TzEhU79RV0KTbEs+2VRzL/wL1VvcvOAxA6B49zzJbjEb0EoaaEOm2o0kPi1S1DSydfhs+9hcbWm7DAfBPmHD/0v8s+zxW5x9jBKTHu3Qm9PsSls48JH37rlUVvcZk96Gaqul882YldhQD/m7RJMDqDqVByOxYhB5dbqJ0kHQDkSPG1zllkFiKe4wEPVxJT11ars0ywXsK3UAJWtmxc0Ii5Viqyd0806EiD6WyAtngDL+O5UwVzB3ZKEHZQtHJoIcyQm0ARfECIAb81scdY/2bGVK+5UleLTqarg2Qdta+swmHgiJgycMKwsVV9iUaekLGKrBfdw9rArDfesRNsZlop2eeDUMdH3wL4AQf4xmEU+vH6tnK0pTSQF0H06fmtW4+BWt8d6dfMXdT4zW+pOUzJNYDIcxTvvdOkoImdTe7Vxw4dtx0W6pnoKubrEfWFaHRiD0JZs9FKC1FyTKEUvV7k3s4uTa/BENOQNfc0aCono5kYBB7Db47SBO+DqZDaF3Wsq9ad/f6QNyfw35UHKGWL77tFg5ZtF83XYs7gmQS/dm7qLpXFcbmhXF7Qhcqz/y5LSpBxfeK7D4wzsdtN8ruz3zUdIkfkAWW1rfMC0qkHywsJYtWdDeJb1wiAWwHsEyolK+SVs/6ACLzYqtzubL9qnM2hWNbdPhbQHHIs1+XQ9oo+1qSAipoyNvrI/uc=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-db-postgresql
      namespace: postgres
