---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-db-postgresql
  namespace: postgres
spec:
  encryptedData:
    postgresPassword: AgCP2urJM0CFAyhXAO8hKAze0yinanaHDw4rbm5ZUzL6JiJeMKv7b2nWmgZYjTRx6NwNi4hu3b1vGe2acTW+FN1A1g4CTaAHHe/WxUik7S0jY06wVa+S0Cj39W2B7HlvUv0hfGv5irCrFYUOVc6rlZnGH/m5neZXlUO9ZmdjlaXXgbosRN4Gzjkt2DcqRqM9hTqoS1fDNWw9RmcfJNaX5r1ErmwntRYxQL8TYv9athTBTnc0/NBkTng7Q7iCMXATSPfAD+bZxgCeoSBvOeF5vec3lnV8fZcWLmb8c8ma7P9kRxV0dUNFjsOChJj3bTaeMhO64/chnS+hqzf+oEu2zH1bWbHHDBHjHhEXnz+ZMWJ+tQkqjWTsnYXY7wgT/2+h6u87wsprfZlAFWQfIcaHfVoCHLYlzCBg2wuqxaL+CyaKvW0cgufrI4599HNnFFE94nfvByiS5H8Oy9DRArYEIvBJIBjB8/+YLq4vPc0mPYjoysDsDRtk7f00nzEeu1FZzLS92bRusdfovMSD0x5zkPkkqhUjZvnbD2PVENwi1yGZtZ28oC8c6kqpLg2I4defcUBbJfiIsg5NFNZpWwk54sCoNJ+g58HgeJcts4xWRTKB4/LOHJByXZQ6bwlCapDZojfBM7rPbB43U6cMoRzGXdPuvrAIyW2snYg/pS0dhorlulaIpUUvxBBfRG47WFuzbwqtse6/23HTV2RXRgtPc4AF6sOhiNdEExwVbHVBI8Y=
    stocksDBPassword: AgCw1L2Iu0DKxtakM4QlDvaBw291R270kRqcNcES2Gc/tYm88v+LyOnInymXpXB38lP4LkZqzX/g45r155cc2tCiUk2sgY+IsnJl/R0VReuisQ0ylnrGltH+Iq2ktVqPgaSp0hPN99T31Xw1rEy8dZxWa9vP6qMr7UjT7wpdKUp0tblaLh74ZJlmsozzcaJKJcc+2YIC2iVEhDnzi2JFrqVAx2ybAIb5hXvO3gpiYy2w8M22UHbtQJpfO85pfevoVrjGISKIMgSmKCkbMkD5CwPU2VF6x+6boFfFA4Lt8hkj8XqtMD1occIfC5rDs4h9Mfhh13pIdACY28SDD6QU9GUc0FFKML7nfqeH7sDdZBomb2ypHNdMeqeHzLhPfU9QAFNwLUajuQWuAnBQ2VFrK3wMC0SFG9ux8kgabTWPd10j5Lk/2PBVJL6KDl8B/q3DrubmkPAcAdn8xF4U3m8ViAiqVFtvLIjgT8VnHnIm+HsfckU2L9jqtLh+bAxu4ZDMhrH6m+NWnRTEoFMPd7OC4i1NscJkygk9lheFkcOgaBgbrl7b1ValR44Jaln/6Yeaw0pWAW8eYJ9G9CApGwXqIzxyvSiWBiMXrj9M15v3cY23aHfTjY9+fHM/ObHWjUktTRxCtT7i/PXsd05ydoegEPWfJh1lP9aNz7McyyJ2PiaJMuYm8z9+0uraxy/at4PaIp9lq3Sttiyi27bDJ5sFpmJkVAXd5ViUJZtlRAYilS0=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-db-postgresql
      namespace: postgres
