---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: postgres
spec:
  encryptedData:
    APP_DB_PASSWORD: AgAGnbmECofUEefIy3oS96PX+VOvWKLkklTMwJnosNAMDvvbv2o70fOpY4Phhu7c+SPAYOtZyWcWOYJxlqAkKl3ElXs1ub6TkjiHkmeDrKWiNGqgbiyXoujwpJ0jHv779e3NkS54c19Rm0+CZJ2EPai2VxUEh5fTP5YcRODXwKTlkgmAsZo+1bSWQYbBO1oGVhwD9LYzhbCv790nRTGNU7eNxE7eHEgqRxksyhvkbn4txfRjFaYM5ygoI5IUjFKhzuGCoIiUwgnva8XFsGVSjWMhL6R8xhMYOVcUkv1vCBS7mjqWoVsERIYqamYPzAcJV4DKjlhYgqpOudYUGk99mpimuWiEpchG3Eq77WunPwnUpKNrCSOkoVCQeKWzFBeGiKE7tjbZZZw5JxC6egKbnt01F5/CYAoRkIlN7y0tYDdQdHaq9Z/XqPVwYrxwhQ4LrB/vBCPOVAkRduAIXclpzC5NoULVgaiDDuvp/UA4UGFfXS8K6QVTE6/cDfDUiGKQ365UktTUZz5dDV1LzvIFNAH6KfF+eeIMldlZW1d3pIKiJ2K3bYcK76ytQUgEw80mwSyFjcbr3T2wRHVAHHX5x3J9ZFSlatV6jNd3UcZK4AXgt2eq9IJdQXS0+3Tdqg9ozrH3pT44CfPtmyjl07h8zppuoQhWpK2I39bEFvHjCWsv3ZygYSXjsXnt1RQrAaeoKRVWfjXR
    password: AgAu+n8EPJcCev8jSqTpNFGkzBIkRviziv97wAKeXPr3sz1Sam5IyglQJDHEkQycDEGMvxCgNkjVAsaW6UKGYAOHLmTIISlh2twwUKOeDHk6SMt0Dn5HYS2moXxbW6NvWBZn1CkhoygACTDkj6MbOWnx/lyllhgbwg7ZN0NLSC8FwqQAh7o2ySoMbbhbsurC2JcL2KabWvQCVdlv2a1dZMjJZ56K451X+p6MhOr64/PMfs+XUa0M9MFvdxrj26x/Evz8UFS/a9aE5jEFhm4i2zZDdt2jHFTxO2xWBVhc8iY7/+MzMoyNHpd+VjNNAlme2oU4ztHO/sXPjabgB2CblvckMCN7UQ4rIWjBQJiFh5/Ta1Wyo+VnvGob3tLmCC/OvtMvYJSaWUMM08UEWdaX7NitT75nE4ExVsjMeprgDyvexxIlDzYGbxkz45i98IOBCjiL36nZhHF/8Pcyob2wnojVJ165+/Ml9qips8HzVzxgBCJjCpMrhum7iwDBHxivlRz/5XKHUcP4MEtopZ/gSJN7kJyCXdrsIIKFphWJHumvzA41ZzzkCTOll14UHESXaOKWH/hPcPZH9POyBjj4iXVIBxeXNmc9l77Y/7O48nicp0Ywlhn7B66dRleMuCZxDbwR+Sb8GIygtmWD+dAsZlyxqTNpBNBQsgLOMK+g14dGpc5KKMl6j8npnB6q2vhmeOen3OtHztSexFs+/HjbshZFadowEs2JiqzDelo3u/E=
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: postgres
