---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: private-repo-creds
  namespace: argocd
spec:
  encryptedData:
    abc: AgBea7pdBtK+pN2s+7JihJQyfZC5yH0x7Z/Pdoh6jRKeDct/Wdpx/XDucj2ZOgjt59n4nNYb6XEjNyBB2qhinD39BYdNrAJ+RFIzpz0M1crHWQL8h3/RcRxKLEKlKBqxNbcGEE9L1xHwC+Qb33Fh/FGlner7h8WxoXU3kd8JAusYUYklEmjSeEPr65tCVmaBku6tY2FqZMWj3N2hvniIbdBNg3+mr8wvnrescE5D3lYBZ4foIrwAbt2uBJbKiDzcpMaVIuJTFIUSgmW4bZQNbhItgx7e3jV1/O/y6EcpqCtgW2q2eXYbWW1ZyZmi58H8JMp1bKaCf2THu806HN1E/HMTK49nJmDDCZkgM0u6Fa/Af4eH5hNTJcu/PqO3ovaLUptfQbkDAfqDNoXUgj3YWVbU0Q1B3prBErJ+Fust8xu8wMuC751YUSk1yPL4Alm0iVFHpAnDTqfp3vCJUYSR1wQVtfRJSj0WCkvlftVOIlypUWDmwETkxivfpT31t50ukP6dx0O0ouWfBVrTocst6Mh6Vo/tg6c3EmnLD8HCEPir2fTmXlKold+JORvDX8P290D0IkAW5ykkrFLiMQz4HEvKDHTjuytpr8hdg8solxofwVIXYCoQO9n1ccOqFHt4WMKyZjHOg+RJuF1pHBO9nor+hNVpFJpmytzOIc9jMNhXLLJlDFe4jX9gayfIIIDp825dzAA=
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: private-repo-creds
      namespace: argocd
