---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-db-postgresql
  namespace: postgres
spec:
  encryptedData:
    APP_DB_PASSWORD: AgCVtPW6IvDoI1YWMqRpszxFhF+AoGhGehbXn8NQlHv4iI3tfRfRgzPRh2akJR7m7kU98f7kF3Rciv+I8Wat2aSKwak9tJlh4T3TIcJvCvLZWQ5MxVfcmOBdmbEaxbgLj2pRhGc5cknnDpaq9QRREXesE+q1GZ9BAJhgt+fsM699d65FanoAzEJv+IqybbgSkvtx2s4SBMLN+fd9dMmxeVQVkso6UbkMrkAg+2tEHRjZMKzRewcV2rorIPm4gfZDYvhwhHqGRPAZ15sqgiA/79VJSdwwCs+jZ3RPJs6ECzwTSwhHRC/XpHXKS08oadGzkSocy12eGwQHtoRqjyWOgoU25ls3gQe6x4ToT0oWpayYBPLTIkAvYIoPztYZ7qWxqNQkhx0rYC0wrwVOsvCc6TJEcCnGvDc/w2StVCa1ZqkSEFoJ/I+VihkuVTaeo8C6IaL8EEYK3cW7kDCQVeO6KglgJWgYI5ioSpm1BG6jg3ZDGdXMdwPW0ez01Hy/a8Ncf+Pe/QuK4MJZ3/MZo0HeO21SnPut/qZCIkKvKd0naK6/+FEvE9Y7B3MkRN6jiZ622eSrQ1YzfSFYe22rasngyTQC6AIOLNx8CFev0HSVJpEAVPmm1cgqK266+BRz3PkY+fX4oL7Y75TSK/pwITN9wMfLruMuOG0NTmXY/tmJanjXfWAyLhmZOU4vWMdiNJ6q6lBPsqZ9
    POSTGRES_PASSWORD: AgAOOcxjpqQbPlgzg9p5Ly0g3DtttRFjv5yZ9XKutr3s8NSPsaJpmenm1/Cnxs9YMlBD8VzmfqqFWGCzBA1fXhJ5GrK0lXx6L8QXgqeU+E1NZB/JI38dCs+CJrjy23QOycOfcWh57GTh34ATJYHIXjqtm0CyxYw5PViIJi3FTteGhkov21DHxemhMU9dxHt5ARHvEwzEkotO1+QtOGlsTijvk7ewBKkZni+0UPGdUfjXik5LJN2P23s9IogVheksCf5cDIJnrcCjnl0oTExtE2xLTYQ2TV5dqsuMomoYLKvrVFuAJykDJQH/xaJSMOM+Zo2Yma7jgQKRr9wlj+m2Go+PRS0X0eG8AyIJWo+rnygODVYnFKvbsGGt6T95x+j7CmghuYfwrBckrNp+VpAd0JPFRIG02Z/NvxllkVu/JUsTQUO/EScflNIdeKBL0uY78yAUnmyEyKVcpS2k+MiZwl4RmD4hXVatlxh56d4urw4cgyTjpako1F8tcOTWE0xk4nCHsL6iU7j5Phhmt5hQU7yV+LhXJdUH5KxSIuI4zcZydH78kwp8iOCn9o5WQv+vp2C5y0Zuhoiya9YqkHkNe37dK5TIV1/ln3iQTVtmTGHEPPVQRjxYCIytZzCXnWTgbsjVNUrKoK6py/UtGoo1Xvpmm4hJdSNIT4RbaZ5uziCTf/+NNaGW3NoRePyaFFzqWdVY/ndOnq5S7gci97eMiosyCjci1K+k9nT/tQxB8kY=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-db-postgresql
      namespace: postgres
