apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db
  namespace: argocd
spec:
  source:
    helm:
      values: |
        global:
          postgresql:
            auth:
              existingSecret: postgres
              username: test
              database: test


