apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db
  namespace: argocd
spec:
  source:
    helm:
      values: |
        global:
          postgresql:
            auth:
              existingSecret: postgres
              secretKeys:
                adminPasswordKey: postgres-password  # Key in the secret for admin password
                userPasswordKey: user-password       # Key in the secret for user password
              username: test
              database: test


