apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  primary.initdb.user: postgres
  stocks_db_username: stocksdb_admin
  stocks_db: stocksdb
  primary.persistence.enabled: "true"
  