apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  values.yaml: |
    global:
      postgresql:
        auth:
          postgresPassword: ${POSTGRES_PASSWORD}
    primary:
      initdb:
        user: postgres
        password: ${STOCKS_DB_PASSWORD}
        extraUsers:
          - name: stocksdb_admin
            password: ${STOCKS_DB_PASSWORD}
            database: stocksdb
      persistence:
        enabled: true
        size: 8Gi
  