apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  values.yaml: |
    primary:
      persistence:
        enabled: true
        size: 8Gi
  