---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: postgres
spec:
  encryptedData:
    postgresPassword: AgC+sMGwISjZThyvURUBBVHUcP1DkU0US+mOQOkLjXeUr7TzEhU79RV0KTbEs+2VRzL/wL1VvcvOAxA6B49zzJbjEb0EoaaEOm2o0kPi1S1DSydfhs+9hcbWm7DAfBPmHD/0v8s+zxW5x9jBKTHu3Qm9PsSls48JH37rlUVvcZk96Gaqul882YldhQD/m7RJMDqDqVByOxYhB5dbqJ0kHQDkSPG1zllkFiKe4wEPVxJT11ars0ywXsK3UAJWtmxc0Ii5Viqyd0806EiD6WyAtngDL+O5UwVzB3ZKEHZQtHJoIcyQm0ARfECIAb81scdY/2bGVK+5UleLTqarg2Qdta+swmHgiJgycMKwsVV9iUaekLGKrBfdw9rArDfesRNsZlop2eeDUMdH3wL4AQf4xmEU+vH6tnK0pTSQF0H06fmtW4+BWt8d6dfMXdT4zW+pOUzJNYDIcxTvvdOkoImdTe7Vxw4dtx0W6pnoKubrEfWFaHRiD0JZs9FKC1FyTKEUvV7k3s4uTa/BENOQNfc0aCono5kYBB7Db47SBO+DqZDaF3Wsq9ad/f6QNyfw35UHKGWL77tFg5ZtF83XYs7gmQS/dm7qLpXFcbmhXF7Qhcqz/y5LSpBxfeK7D4wzsdtN8ruz3zUdIkfkAWW1rfMC0qkHywsJYtWdDeJb1wiAWwHsEyolK+SVs/6ACLzYqtzubL9qnM2hWNbdPhbQHHIs1+XQ9oo+1qSAipoyNvrI/uc=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-db-postgresql
      namespace: postgres
