---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db
  namespace: postgres
spec:
  encryptedData:
    postgresPassword: AgCcVbLZURo28K4jVENKHrJa5Ih675+9Q93whoQqqOTpisYPb+yyXDIVttZls8xv22RI0GCDHoUwEQpRVuAs7R6wkEhyp7Y83xRoaScTSTgCzLFK1I9KwcYbYGq9b3mMnNpEUGYL9PpvlQ9E6UNP9ut3XwotyIo7JLm98X09aLQk6Ydekm4OEcjPbfeqKwVYSjXBHU3luCFDcy5K1wvjHurJ5kKJYV4dBVvBA9MgEQROS+8x4NR33wnOabAEwQ5IjCKEQTyCSpvj3cBBqJR7oOrvRWq/4djTaRUnz6H5wPHFSOG8+luiaZzKt/HaAs7j50sG2Y9btfHsPtaiVN8V3JeIxEFKTYLBY4O2rS0ZFuPeQoHkSD6oJ8U3HVdtROHZPiROtcSr9LIH1myqasz33kGBaj9oNW8E2M8BvRP0+OO+FMAYkgP9KtvCP3JP4IXPChQM2o16TTcXw+D20BdxB8SqMwLaZjGc+lAznegBGZ4dBAH0BTATFJujtKG/B1K6ifNu1IS/dPHKISIWGXf19gBhljShvpNw22IpmtWa6Un8T9C0pOdOie8Ivg6MmPQ3v+nP3cP2ob2GRsOzS+N8/P6YEamGaPZajIi6y+nszICnBazgu+mL2pwoVi80e3IBuEz66x7ub0QIQ80u8mhjrvz0TZWy0hOyiflwpJQme2anpAH9VxSsBAEv7OxcotPWAGd7oKOwXSRPsV5llqw1UZMcVepuGLvDQppPLDd8XR4=
    stocksDBPassword: AgDJbHxZE/zZ7/M7TmtcOgTY2TeON+vqtdZOtmnXAj/7G2ZhqI+JPQUiRvYtO3xfhY9cWLUP8wY7dWjKvrlO73rOuTAukpbpCLRlSlpoBhYgvJu1wRk+ZLnHKYU/GxOpBLn0bn8cAKoHuUpnCL/js5kt6dm+d/7W/8kLOyP7Cxk9C2GNbTYaA4F6HHs1u3Ayi+uqoPU2jx3wG/iSKT8iboHCf6/ZHB6O+jwyLvFrRBlEAn0oAxywe4qDOcqy7alLEM76tRJgtPdmXG9E2l03uqiSCa1qIVBMwbjnEPYsS4J0rinGbOq23hBHHKK9kYFw7vYm6tsW0gmdOQd6yoHTsA2MnwpgBrOyR3flpKjOcIyknyhwjL5RVxwqJaEdhKOZea6OdIHLcHSNLih4Fhv4TT+qSIlAreOak1TYJDpNdrInnFMBtlkIiH6CP0nj7u5QDZzhltFfZNfBCN5SdZQ0WBH3CZNgsR5eYFFOlPqOVdkMGOy/JdjsXyE8b8e7ORZ3VLY1uOjvKxcto9DLuXwrsdo+xSvO6dRmkeR8m9UXEPVnYwfysI+uVT6kBIh1gIs1xxZbs7C2LKkZNetqRff6GTwAZS3FqpHl3NAWEUGv0XnTnf42Csq+gS/oGAoGi6ThczqAFR0D0IW82mquKDvez6tjUR/UnxOJcMBU71mLY5KYvawUIrz0sQkvH3z1uW4N3iEu3ifhu7GFm7r9zK0wvrvCPtKbawek6EnRl/5qDUE=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-db
      namespace: postgres
