apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: postgres
spec:
  encryptedData:
    auth.postgresPassword: AgCP2urJM0CFAyhXAO8hKAze0yinanaHDw4rbm5ZUzL6JiJeMKv7b2nWmgZYjTRx6NwNi4hu3b1vGe2acTW+FN1A1g4CTaAHHe/WxUik7S0jY06wVa+S0Cj39W2B7HlvUv0hfGv5irCrFYUOVc6rlZnGH/m5neZXlUO9ZmdjlaXXgbosRN4Gzjkt2DcqRqM9hTqoS1fDNWw9RmcfJNaX5r1ErmwntRYxQL8TYv9athTBTnc0/NBkTng7Q7iCMXATSPfAD+bZxgCeoSBvOeF5vec3lnV8fZcWLmb8c8ma7P9kRxV0dUNFjsOChJj3bTaeMhO64/chnS+hqzf+oEu2zH1bWbHHDBHjHhEXnz+ZMWJ+tQkqjWTsnYXY7wgT/2+h6u87wsprfZlAFWQfIcaHfVoCHLYlzCBg2wuqxaL+CyaKvW0cgufrI4599HNnFFE94nfvByiS5H8Oy9DRArYEIvBJIBjB8/+YLq4vPc0mPYjoysDsDRtk7f00nzEeu1FZzLS92bRusdfovMSD0x5zkPkkqhUjZvnbD2PVENwi1yGZtZ28oC8c6kqpLg2I4defcUBbJfiIsg5NFNZpWwk54sCoNJ+g58HgeJcts4xWRTKB4/LOHJByXZQ6bwlCapDZojfBM7rPbB43U6cMoRzGXdPuvrAIyW2snYg/pS0dhorlulaIpUUvxBBfRG47WFuzbwqtse6/23HTV2RXRgtPc4AF6sOhiNdEExwVbHVBI8Y=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-db-postgresql
      namespace: postgres
