apiVersion: v1
kind: Secret
metadata:
  name: postgres-values
  namespace: postgres
type: Opaque
stringData:
  values.yaml: |
    global:
      postgresql:
        auth:
          postgresPassword: abc
    primary:
      initdb:
        user: postgres
        password: bcd
        extraUsers:
          - name: stocksdb_admin
            password: cde
            database: stocksdb
      persistence:
        enabled: true
        size: 8Gi
        