auth:
  enablePostgresUser: true
  existingSecret: postgres-db-postgresql
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: APP_DB_PASSWORD

primary:
  primary:
    persistence:
      enabled: true
      size: 8Gi

  pgHbaConfiguration: |
    host all all 0.0.0.0/0 md5
    local all all trust
