apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd.yaml
- root.yaml
# - ../../applications/data-collector-service #4
- ../../applications/data-sync # 3
- ../../applications/sealed-secrets # 1
- ../../applications/traefik # 2
- postgres.yaml # 4
- rabbitmq-operator.yaml # 5


patches: 
- path: data-sync/target-patch.yaml

