apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd.yaml
- root.yaml
# - ../../applications/data-collector-service #4
- ../../applications/data-sync
- ../../applications/sealed-secrets
- ../../applications/traefik
- postgres-operator.yaml
- postgres-cluster.yaml
- rabbitmq-operator.yaml
- rabbitmq-cluster.yaml


patches: 
- path: data-sync/target-patch.yaml

