apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd.yaml
- root.yaml
# - ../../applications/data-collector-service #4
# - ../../applications/rabbitmq-service #3
- ../../applications/data-sync # 3
- ../../applications/sealed-secrets # 1
- ../../applications/traefik # 2

