apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/stocks-analyser/stocks-gitops-infra"
    path: environments/development/postgres-operator
    targetRevision: dev
    kustomize:
      commonAnnotations:
        managed-by: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true   # <<--- important
