apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/stocks-analyser/stocks-gitops-infra"
    path: environments/development/postgres
    targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd