apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/stocks-analyser/stocks-gitops-infra"
    path: environments/development/rabbitmq-cluster
    targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true  
