apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.0
    helm:
      # releaseName: postgres-db
      values: |
        global:
          postgresql:
            auth:
              postgresPassword: abc
        primary:
          initdb:
            user: postgres
            password: bcd
            extraUsers:
              - name: stocksdb_admin
                password: cde
                database: stocksdb
          persistence:
            enabled: true
            size: 8Gi
 

  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
