apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-dev
  namespace: pgdb
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret
