apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app
  namespace: pgdb
spec:
  encryptedData:
    APP_DB_PASSWORD: AgAurzFPx2cnbv+hka/erK2lFlPgKflypCUZPqOM3qlhvp8Y3bfiZtOTrY3F8X4omTFSIwX795kNhRsdCd0a+Ze5OzYYTnQ+5tY+dJoEVuEPnmXyBFJAWJw5CxB36m5USa3D6tNwk4dAjvIQbTmoaBs1XRtMzLzYzPa6QIU6kkCBwQ10zuKXvrbuRUVU594LF+aPkO6CpcBL5ZZ+qG1pZVhIp+RgpmWM/rJKiNdlO3C6mBEGmQ36pyiNKRZkgTicG169qnhRFA3iz9kbi5+kpzt+5sW32Fv03nTLmrXTlDtL8x3X53GBsdHC2XRblGtTSEKn184AFWmGHEIAMky/1/4quN13+AvFiP+z+6Zua/gV0t1xRBHx4CjX23JSWyZX1kBSZOQkpxwaVE6O+h/sOranrp+C45N5QZjWA1gUuaxMo8S7O8lY+5ZGpyvJqFlxWafcD05BSI0mT2xlITVIIYFrIfkZ4jgp5UGodOL/cP4Kr/cHgdLs2xdInH+IFiKfplTlOgKIlSt3E/TkEIhUD/B/0Z+ikfDs0TULyr/na2SGv4V/ghwhSqZJGtekJatVInMNfnQSA98uYrgWSh7dhqSh+yjCsJJPEHlG4uwOZK7QEvOgyuKZfuO2iqqZtilNIdZyM7VR29nSRaaTcwcOoZiD/LCTPVn4cxBRGfC4T0IbDl/WO/v3v8gB8bSva80nwbvn1e+0usvN3U0CM4GmBnnAcs66lSlD5HL5I9fKUH8=
  template:
    metadata:
      creationTimestamp: null
      name: app
      namespace: pgdb
