apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: ghcr.io/alejandropriv/stress-image:latest
    imagePullPolicy: Always
  imagePullSecrets:
  - name: dockerconfigjson-github-com
