apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stocks-data-sync-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: "https://github.com/stocks-analyser/stocks-data-sync.git"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
    