---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stocks-data-sync
  namespace: stocks-data-sync
spec:
  encryptedData:
    ALPHAVANTAGE_API_KEY: AgAl6TDvXpm/KJGlmCl3Qgb9rAEoblxP+EFv843GAbptymVw0wqh07GfgfGnhy3sO8tIINIkUL3Ahb5kCBnW7dygrFH/Kv7lvjp5WTcfcaLS0kXQl80C8it+hvDxbo+idSiZUuCQMm9Hun99z36J3G8w1khJOS3LdNF+E0iMnraS9fb6CFX7QZbSn0dzapg47gq5xE+iTxJo7QGjxpcSboA+Yev6ILhACb+Z1ICimwy9OQnGh0sQNRwdOeafgRUxEkaPk/ErsHLeErUdR4hGId0jK+0vMxX8sUX21A7318lanEWe3EjtPSSbJFYZDYHrNiQ7EOFt7apkI2vvtMVNzRQ4ToY7gSVN4MiViCDkm724eYNQqCZSZvToy2if2alfcE6cwiz/qDOArYnBf1Y1N1l2ffaZXJpXC7ZLgbmVD2wCiBO5a9zfHy1K/obiFxZZtzWArbGFQg/dcESzILk458BfB9tZcLsglgRkFHcMZdOMoTE3xqOTa0vqtEZzUhiARP1Rb3yqczyP/tCdB5T+3yE66lmncqmraTfPCYwp83bJkzriLPIk3fu7kbNitLLpVyvapZ7sP/b2NakOp2sf8BXXGYRHS3HDixkMTBQICMr070akZVGa6YDgf9OKFW83X/MFzJB95EdfgJVf7gafgbOHCKoTVrK77PP3X9Vno8qbXMVj5kWWFqSe3ssdTS+9zb6dll8KG67LgSP/bpEsKYue
  template:
    metadata:
      name: stocks-data-sync
      namespace: stocks-data-sync
